### ISSUE TITLE
incomplete solution, i wantg my money back

### ISSUE THREAD

**Issue by JuanZamudio** [netor27/OrdersSystem#3]
![capture](https://cloud.githubusercontent.com/assets/28059166/25493889/5981803a-2b3d-11e7-9667-ffeeccf132db.PNG)

**Comment by netor27** [comment]
mames, ¿qué rompiste?

**Comment by JuanZamudio** [comment]
git que no funciona, is not enterprise ready

**Comment by netor27** [comment]
ya le hiciste el fetch?
ojalá este link te funcione:
http://lmgtfy.com/?q=how+to+git+fetch

**Comment by JuanZamudio** [comment]
fue desde hace rato, ahorita ya tengo todo al tiro
